# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zodi Bell
subtitle: Logophile, Mama, Observer
name: Zodi Bell
# email: zodibell7@gmail.com
description: A home for Zodi's musings.
#  Write an awesome description for your new site here. 
# You can edit this line in _config.yml. 
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zodibell.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: zodibell/zodibell.github.io
logo: /assets/images/zb_logo_1.png
paginate: 9  # Number of posts per page (optional)
paginate_path: "/page:num/"
permalink: /:categories/:title/
future: true

# breadcrumbs: true (use a category-based permalink structure before enabling)

# twitter_username: jekyllrb
github_username:  zodibell

# Build settings
# source: "https://rubygems.org"
source: .
destination: ./_site

# Gem Dependencies - Ensure Gemfile matches
# gem "github-pages", group: :jekyll_plugins
# gem "jekyll-include-cache", group: :jekyll_plugins

# Jekyll settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"
locale: "en-US"
defaults:
  # _posts
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default" 
      author_profile: false
      share: true
      related: true 
      show_date: true
      comments: false 
      # read_time: true
      # words_per_minute: 250 (standard is 200)

date_format: "%B %-d, %Y"
search: true 
lunr:
  search_within_pages: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-tags
  - jekyll-target-blank
  - jekyll-archives


# Pagination settings
paginate: 9 # Posts per page
paginate_path: "/page:num"

collections:
  posts:
    output: true

tag_archive:
  path: /tags/
  type: jekyll-archives 

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: /tags/:name/


sass:
  sass_dir: "assets/css"  # Ensure this matches your actual SCSS file location

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - tags
  
exclude:
  - pages
  - drafts


