# _plugins/generate_tag_pages.rb
require 'fileutils'

module Jekyll
  class TagPageGenerator < Generator
    safe true
    priority :low  # runs after posts and data are loaded

    def generate(site)
      tags_dir = 'tags'

      # --- Collect all tags from posts ---
      post_tags = site.posts.docs.flat_map do |post|
        post.data['tags'] || []
      end.map(&:to_s)

      # --- Collect all tags from vocabulary data ---
      vocab_tags = []
      if site.data['vocabulary']
        vocab_tags = site.data['vocabulary'].flat_map do |entry|
          entry['tags'] || []
        end.map(&:to_s)
      end

      # --- Merge, normalize, and remove duplicates ---
      all_tags = (post_tags + vocab_tags).map(&:downcase).uniq

      # --- Generate individual tag pages ---
      all_tags.each do |tag|
        slug = tag.downcase.strip
                  .gsub(/\s+/, '-')           # replace spaces with dash
                  .gsub(/[^\w-]/, '')         # remove non-word characters
                  .gsub(/-+/, '-')            # collapse multiple dashes

        # Skip the main /tags/ page to avoid conflicts
        next if slug == '' || slug == 'tags'

        tag_folder = File.join(tags_dir, slug)
        FileUtils.mkdir_p(tag_folder)

        File.open(File.join(tag_folder, 'index.md'), 'w') do |file|
          file.puts <<~MARKDOWN
            ---
            layout: tag
            tag: #{tag}
            title: Posts tagged "#{tag}"
            permalink: /tags/#{slug}/
            ---
            <!-- Auto-generated by generate_tag_pages.rb -->
          MARKDOWN
        end
      end

      Jekyll.logger.info "TagPageGenerator:", "Generated #{all_tags.size} individual tag pages"
    end
  end
end
